name: hr-llm
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - expat=2.7.4=hd7fb8db_0
  - libexpat=2.7.4=hd7fb8db_0
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.0.19=hbb43b14_0
  - packaging=25.0=py311haa95532_1
  - pip=25.3=pyhc872135_0
  - python=3.11.14=h981015d_0
  - setuptools=80.10.1=py311haa95532_0
  - sqlite=3.51.1=hda9a48d_0
  - tk=8.6.15=hf199647_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.46.3=py311haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - accelerate==1.12.0
      - aiosqlite==0.22.1
      - altair==6.0.0
      - annotated-types==0.7.0
      - anyio==4.12.1
      - attrs==25.4.0
      - bitsandbytes==0.49.1
      - blinker==1.9.0
      - cachetools==6.2.6
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - click==8.3.1
      - colorama==0.4.6
      - distro==1.9.0
      - filelock==3.20.3
      - fsspec==2026.1.0
      - gitdb==4.0.12
      - gitpython==3.1.46
      - greenlet==3.3.1
      - groq==1.0.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.3.7
      - idna==3.11
      - jinja2==3.1.6
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - markupsafe==3.0.3
      - mpmath==1.3.0
      - narwhals==2.16.0
      - networkx==3.6.1
      - numpy==2.4.2
      - pandas==2.3.3
      - pillow==12.1.0
      - protobuf==6.33.5
      - psutil==7.2.2
      - pyarrow==23.0.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydeck==0.9.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - pytz==2025.2
      - pyyaml==6.0.3
      - referencing==0.37.0
      - regex==2026.1.15
      - reportlab==4.4.9
      - requests==2.32.5
      - rpds-py==0.30.0
      - safetensors==0.7.0
      - sentencepiece==0.2.1
      - shellingham==1.5.4
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - sqlalchemy==2.0.46
      - streamlit==1.53.1
      - sympy==1.14.0
      - tenacity==9.1.2
      - tokenizers==0.22.2
      - toml==0.10.2
      - torch==2.10.0
      - tornado==6.5.4
      - tqdm==4.67.2
      - transformers==5.0.0
      - typer-slim==0.21.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - urllib3==2.6.3
      - watchdog==6.0.0
prefix: C:\Users\modhi\anaconda3\envs\hr-llm
